Update authentik.mdx to specify that the trailing slash IS required
Currently the documentation says that you add the URL with the slug without a trailing slash explicitly, but it is actually the exact opposite. Authentik will not work without the trailing slash. You will receive this error: 

OperationProcessingError: "response" body "issuer" does not match "expectedIssuer"

until you add that trailing slash.