Use getReposistory instead of getManager
Both getRepository and getManager were being used, not only is it inconsistent, but getManager does not respect connection name specified in config. 

Found this bug when testing Linkedin custom provider, even though I had 
`
const options = {
  database: {
    type: 'postgres',
    name: 'next-auth-connection',
    url: process.env.DATABASE_URL,
    synchronize: process.env.NODE_ENV !== 'production',
  },
...
}
`

I was still getting this error
`
[next-auth][error][CREATE_USER_ERROR] [
  ConnectionNotFoundError: Connection "default" was not found.
`