Support importing "next-auth/react" in Server Component environment
Currently, importing "next-auth/react" in a Server Component module (or in a module imported by a Server Component module) will fail with `Uncaught TypeError: React.createContext is not a function`.

This is because React Context is unavailable in Server Components.

With this change, "next-auth/react" can be imported without error, and an informative error is thrown if there's an attempt to actually *use* React Context.